{"name": "test_login_fail[data2]", "status": "passed", "attachments": [{"name": "log", "source": "552c7357-9121-4e12-b6db-624e831521c7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'id': 3, 'title': '6位错误验证码', 'url': 'http://192.168.3.157:8069/dongwang-app/app/user/login', 'json': {'type': '1', 'flashToken': '', 'deviceId': 'aaa', 'device': '1', 'smsCode': '123456', 'phone': '113157121093'}, 'expected': {'status_code': 500, 'message': '验证码输入错误,请重新输入'}}"}], "start": 1614570648336, "stop": 1614570648370, "uuid": "db824f26-c20d-4626-aa80-f2aa8c90dcb3", "historyId": "490f94efd3791f18d8a00ee815ee620a", "testCaseId": "a67639c7d108120b92ca3b258a406cc7", "fullName": "testcase.test_login.TestLogin#test_login_fail", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "错误验证码"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SC-201907251023"}, {"name": "thread", "value": "11476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}